app_name = "habibi_ai"
app_title = "Habibi AI"
app_publisher = "Habeebe"
app_description = "ИИ-модуль: чат в desk ERPNext поверх движка Directus"
app_email = "dosnet2200@gmail.com"
app_license = "mit"
